### ISSUE TITLE
Tests for linreg

### ISSUE THREAD

**Issue by rezayas** [rezayas/ComputationalLib#13]
Test if you can fit **y = 1 + 2x1 - 3x3** under these scenario (notice the minus sign before 3):

using the regular LS (close-form formula) with no omega or lambda
using the regular LS (close-form formula) with omega = 0.001 or lambda = 1
using the regular LS (close-form formula) with omega = 0.001 or lambda = 0.95
using the regular LS (close-form formula) with omega = 0 or lambda = 0.95
using the updating algorithm with no omega or lambda
using the updating algorithm with omega = 0.001 or lambda = 1
using the updating algorithm with omega = 0.001 or lambda = 0.95
using the updating algorithm with omega = 0 or lambda = 0.95

**Comment by NoLongerBreathedIn** [comment]
Done

**Comment by rezayas** [comment]
Thanks. Questions:
1. Shouldn't we get the same numbers for Test 3 and Test 7? 
2. Shouldn't we get the same numbers for Test 4 and Test 8?

**Comment by NoLongerBreathedIn** [comment]
Yeah, I don't know what's going on here.

**Comment by rezayas** [comment]
Note when omega > 0, then b should be initialized after the first row is entered using b = (xᵀwx + ωI)⁻¹.
here: x is 1 by D, W is 1 by 1, I is D by D and omega is an scalar, So b will be D by D. 

I think it will fix it. try it.

**Comment by NoLongerBreathedIn** [comment]
I'm initializing it before the first row is entered as b = I/w.

**Comment by rezayas** [comment]
yes I saw it and I think that's not correct. it's an ok initialization but the exact approach is to initialize b as (xᵀwx + ωI)⁻¹ once the first row is entered.

**Comment by NoLongerBreathedIn** [comment]
It's EQUIVALENT, and this uses LESS code.

**Comment by NoLongerBreathedIn** [comment]
After all, I am initializing b BEFORE the first row is entered, so there is NO issue here.

**Comment by rezayas** [comment]
feel free to try different things but I think the issue is with the initialization of b.  

when omega > 0, these lines should be executed after the first row: 
     auto c = (xmat.transpose() * wvec.asDiagonal() * xmat
		  + mat::Identity(pdim, pdim) * omega).ldlt();
    b = c.solve(mat::Identity(pdim, pdim));
   theta = c.solve(xmat.transpose() * wvec.cwiseProduct(yvec));

but I think the condition if(points >= pdim) that you have there doesn't allow it.

**Comment by NoLongerBreathedIn** [comment]
Or we could initialise b before the first row gets in and just update it every time? It's mathematically equivalent and faster.

**Comment by rezayas** [comment]
yes. then maybe you should change 

if(points >= pdim)

to 

if(points >= pdim or omega > 0)

not sure. you should test it.

**Comment by NoLongerBreathedIn** [comment]
Wouldn't make a difference, if we get there omega <= 0 anyway.

**Comment by rezayas** [comment]
from you code, it seems that when omega is > 0 you still wait until (points >= pdim) is satisfied. And that doesn't get satisfied until you have enough rows. 

When omega > 0, you should NOT wait and you SHOULD update b and theta as soon as the first row is entered.

**Comment by NoLongerBreathedIn** [comment]
No, I set ready = omega > 0 in LinearRegression::reset().

**Comment by rezayas** [comment]
Then, I am positive that you are not initializing b correctly. look

you set b = Eigen::MatrixXd::Identity(idim, idim) / omega

and after the first row, you run 
       double gamma = lambda + (x.transpose() * b * x)(0,0);
      theta += (b * x * (y - theta.transpose() * x) / gamma).eval();
      b -= (b * x * x.transpose() * b / gamma).eval();

This is not the correct sequence. 
You should first initialize b as  b = (xᵀwx + ωI)⁻¹, where w is set to first lambda and then update theta.

**Comment by NoLongerBreathedIn** [comment]
Um, what?
I set b = I/w, then b' = inv(trans(x)x + inv(b * lambda)), right? Or is my code messed up somewhere?
I mean, if this works for the second and subsequent x, then it should work for the first as well.

**Comment by rezayas** [comment]
I don't know Eyal. Just give this a try: 

after the first row is entered: 
- Initialize b as b = (xᵀwx + ωI)⁻¹ right after the first row (remember w is equal to the entered lambda). 
- then calculate theta

see if it works. it doesn't take much of your time.

**Comment by NoLongerBreathedIn** [comment]
Wait a minute, isn't that backwards? Shouldn't we initialize it as `b = inv(trans(x)x + wlI)`?

**Comment by rezayas** [comment]
no, the matrix of lamdas is in between xT and x and,  the matrix of omega*I is added: b = (xᵀwx + ωI)⁻¹

w is the matrix of lambdas, but right after the first row, w is just an scalar and is set to the entered lambda.

**Comment by NoLongerBreathedIn** [comment]
Hang on, why isn't it set to 1?
See the equivalent definition in the direct regression version.

**Comment by rezayas** [comment]
good point. then initialize  b = (xᵀx + ωI)⁻¹

**Comment by NoLongerBreathedIn** [comment]
That's what I'm doing; I'm just doing it in a slightly different way.

**Comment by rezayas** [comment]
Let me know when you synced so that I check it too.

**Comment by NoLongerBreathedIn** [comment]
I didn't make any changes. I'm synced up.

**Comment by rezayas** [comment]
The numbers don't match... 

Line 85 in linreg.cpp should change to: 
b -= (b * x * x.transpose() * b / gamma).eval()/lambda;

I double checked the formula.

**Comment by rezayas** [comment]
are you initializing  b using b = (xᵀx + ωI)⁻¹?

**Comment by NoLongerBreathedIn** [comment]
Changed. AND I FIXED THAT. I'm doing that while x still has no rows.

**Comment by rezayas** [comment]
the numbers still don't match. I am going to think more about it but this needs to be fixed.

**Comment by NoLongerBreathedIn** [comment]
Well, I can't figure it out either.

**Comment by NoLongerBreathedIn** [comment]
Oh, there's an issue:  Sherman-Morrison says b -= `(b * x * x.transpose() * b / x.dot(b * x)).eval(); b /= lambda;` is correct.
Now checking theta-update.

**Comment by NoLongerBreathedIn** [comment]
And it's fixed and pushed.

**Comment by rezayas** [comment]
That's correct but still Test 4 and 8 don't give the same estimates.  There must be a bug somewhere else.

**Comment by NoLongerBreathedIn** [comment]
Found the bug! It's in the following line:
`for(int i = ys.size() - 1, p = 1; i >= 0; i--, p /= lambda)`
First, that `/=` should be a `*=`, and second, I accidentally declared `p` as an integer.
Fixing both of those fixed the issue.

**Comment by NoLongerBreathedIn** [comment]
I also turned `w` in the same function into a vector instead of a matrix. This speeds up the code considerably.

**Comment by rezayas** [comment]
Nice, thanks Eyal!
